version: '3'
services:
  hrm-app:
    container_name: hrm-app
    build:
      context: .
      args:
        NODE_ENV: '${APP_ENVIRONMENT}'
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '5057:5056'
    environment:
      - ./.env

    command: yarn '${APP_ENVIRONMENT}'

  mariadb:
    image: mariadb:10.6
    container_name: hrm-mariadb
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - app-mariadb:/var/lib/mysql # Define the volume here
    networks:
      - app
    restart: on-failure
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
      retries: 3
      timeout: 5s

  mailhog:
    image: mailhog/mailhog:latest
    container_name: hrm-mailhog
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - app

  redis:
    image: redis:alpine
    container_name: hrm-redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - app-redis:/data
    networks:
      - app
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
volumes:
  app-mariadb:
    driver: local
  app-redis:
    driver: local
networks:
  app:
    name: app
    driver: bridge
    external: false
